all:
	echo "make"
	gcc ArvBinBusca.c -o ArvBinBusca.o
	gcc TestaArvBinBusca.c -o TestaArvBinBusca

run:
	echo "Rodando"
	./TestaArvBinBusca.exe
clean:
	echo "Limpando"
	rm ./*.exe 
	rm ./*.o

list:
	echo "listando"
	ls .